#!/usr/bin/env bash
#script that installs Nginix and redirects to another page

apt-get -y update
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.ngnix-debian.html
sed i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/ngnix/sites-available/default
service ngnix restart
