#!/usr/bin/env bash
#script that doubles number of web servers

apt-get -y update ; 
apt-get -y install nginx

str="http {\n\tadd_header X-Served-By \"$hostname\";"
sudo sed -i "s/http {/$str/" /etc/nginx/sites-available/default

sudo service nginx restart
