#!/usr/bin/env bash
# A Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration                    
# I am invincible!!! when receiving a SIGTERM signal
msg="I am invincible!!!"
trap 'echo $msg' 15
while true
do
 echo "to infinity and beyond"
 sleep 2
done
