#!/usr/bin/env bash
# Uses while loop and if elif else

iter="0"

while [ $iter -lt 10 ]
do
if [ $iter -eq 3 ]
then
 echo "bad luck"
elif [ $iter -eq 7 ]
then
 echo "good luck"
else
 echo "Best School"
fi
iter=$((iter + 1))
done
